{'profile': {'patient_id': 'otto',
             'patient_name': 'Otto',
             'profile_id': 'otto_profile',
             'age_group': 'elderly_65_plus',
             'education_level': 'middle_school_graduate',
             'health_literacy_level': 'low',
             'main_communication_need': 'Understand diagnosis without '
                                        'unnecessary alarm',
             'condition_id': 'cll',
             'condition_name': 'Chronic Lymphocytic Leukemia',
             'condition_abbreviation': 'CLL'},
 'dominant_barriers': [{'factor_id': 'health_literacy_level',
                        'factor': 'Health literacy level',
                        'factor_type': 'health_literacy',
                        'factor_value': 'low',
                        'factor_value_type': 'categorical',
                        'health_literacy_dimension': 'Understand',
                        'influence_weight': 0.9,
                        'computed_influence_score': None,
                        'direction': 'negative',
                        'effect': 'Lower health literacy reduces ability to '
                                  'understand standard medical explanations',
                        'evidence_status': 'profile_defined_provisional',
                        'needs_validation': True},
                       {'factor_id': 'medical_knowledge',
                        'factor': 'Medical knowledge',
                        'factor_type': 'knowledge',
                        'factor_value': 'low',
                        'factor_value_type': 'categorical',
                        'health_literacy_dimension': 'Understand',
                        'influence_weight': 0.85,
                        'computed_influence_score': None,
                        'direction': 'negative',
                        'effect': 'Lower medical knowledge makes technical '
                                  'terminology harder to understand',
                        'evidence_status': 'expert_informed_provisional',
                        'needs_validation': True},
                       {'factor_id': 'memory',
                        'factor': 'Memory',
                        'factor_type': 'cognitive',
                        'factor_value': 'possible_deficit',
                        'factor_value_type': 'inferred_categorical',
                        'health_literacy_dimension': 'Understand',
                        'influence_weight': 0.75,
                        'computed_influence_score': None,
                        'direction': 'negative',
                        'effect': 'Lower memory capacity reduces retention of '
                                  'key information',
                        'evidence_status': 'inferred_for_vertical_slice',
                        'needs_validation': True},
                       {'factor_id': 'worry_anxiety',
                        'factor': 'Worry / anxiety',
                        'factor_type': 'emotional',
                        'factor_value': 0.85,
                        'factor_value_type': 'numeric',
                        'health_literacy_dimension': 'Appraise',
                        'influence_weight': 0.85,
                        'computed_influence_score': 0.7224999999999999,
                        'direction': 'negative',
                        'effect': 'Higher worry makes health information '
                                  'harder to appraise calmly',
                        'evidence_status': 'expert_informed_provisional',
                        'needs_validation': True},
                       {'factor_id': 'educational_level',
                        'factor': 'Educational level',
                        'factor_type': 'sociodemographic',
                        'factor_value': 'middle_school_graduate',
                        'factor_value_type': 'categorical',
                        'health_literacy_dimension': 'Understand',
                        'influence_weight': 0.7,
                        'computed_influence_score': None,
                        'direction': 'negative',
                        'effect': 'Lower educational level requires simpler '
                                  'syntax and shorter text blocks',
                        'evidence_status': 'profile_defined_provisional',
                        'needs_validation': True},
                       {'factor_id': 'age',
                        'factor': 'Age',
                        'factor_type': 'sociodemographic',
                        'factor_value': 'elderly_65_plus',
                        'factor_value_type': 'categorical',
                        'health_literacy_dimension': 'Understand',
                        'influence_weight': 0.65,
                        'computed_influence_score': None,
                        'direction': 'negative',
                        'effect': 'Older age may require '
                                  'accessibility-oriented presentation',
                        'evidence_status': 'profile_defined_provisional',
                        'needs_validation': True},
                       {'factor_id': 'uncertainty',
                        'factor': 'Uncertainty',
                        'factor_type': 'emotional',
                        'factor_value': 0.8,
                        'factor_value_type': 'numeric',
                        'health_literacy_dimension': 'Appraise',
                        'influence_weight': 0.8,
                        'computed_influence_score': 0.6400000000000001,
                        'direction': 'negative',
                        'effect': 'Higher uncertainty makes prognosis and '
                                  'disease meaning harder to appraise',
                        'evidence_status': 'expert_informed_provisional',
                        'needs_validation': True},
                       {'factor_id': 'processing_speed',
                        'factor': 'Processing speed',
                        'factor_type': 'cognitive',
                        'factor_value': 'possible_deficit',
                        'factor_value_type': 'inferred_categorical',
                        'health_literacy_dimension': 'Understand',
                        'influence_weight': 0.6,
                        'computed_influence_score': None,
                        'direction': 'negative',
                        'effect': 'Lower processing speed requires '
                                  'slower-paced stepwise explanations',
                        'evidence_status': 'inferred_for_vertical_slice',
                        'needs_validation': True}],
 'adaptation_instructions': [{'category': 'Content - Lexical',
                              'adaptation_element': 'Complexity of medical '
                                                    'terms',
                              'triggering_factor': 'Health literacy level',
                              'factor_value': 'low',
                              'activation_weight': 0.9,
                              'computed_activation_score': None,
                              'text_effect': 'Explain CLL immediately after '
                                             'naming it',
                              'text_features': ['Term explanation']},
                             {'category': 'Content - Lexical',
                              'adaptation_element': 'Simplified Language',
                              'triggering_factor': 'Health literacy level',
                              'factor_value': 'low',
                              'activation_weight': 0.9,
                              'computed_activation_score': None,
                              'text_effect': 'Use common words and direct '
                                             'explanations',
                              'text_features': ['Language complexity']},
                             {'category': 'Content - Syntax & Grammar',
                              'adaptation_element': 'No conditionals',
                              'triggering_factor': 'Health literacy level',
                              'factor_value': 'low',
                              'activation_weight': 0.9,
                              'computed_activation_score': None,
                              'text_effect': 'Avoid complex if-then '
                                             'constructions where possible',
                              'text_features': ['Conditional complexity']},
                             {'category': 'Morphology / Formatting',
                              'adaptation_element': 'Text block size',
                              'triggering_factor': 'Health literacy level',
                              'factor_value': 'low',
                              'activation_weight': 0.9,
                              'computed_activation_score': None,
                              'text_effect': 'Use short paragraphs and avoid '
                                             'dense text blocks',
                              'text_features': ['Paragraph density']},
                             {'category': 'Content - Lexical',
                              'adaptation_element': 'Simplified Medical Terms',
                              'triggering_factor': 'Medical knowledge',
                              'factor_value': 'low',
                              'activation_weight': 0.85,
                              'computed_activation_score': None,
                              'text_effect': 'Use blood cancer instead of '
                                             'hematological malignancy',
                              'text_features': ['Terminology complexity']},
                             {'category': 'Morphology / Formatting',
                              'adaptation_element': 'Bold',
                              'triggering_factor': 'Memory',
                              'factor_value': 'possible_deficit',
                              'activation_weight': 0.75,
                              'computed_activation_score': None,
                              'text_effect': 'Bold only the most important '
                                             'terms or messages',
                              'text_features': ['Emphasis']},
                             {'category': 'Morphology / Formatting',
                              'adaptation_element': 'Bullet Points/Lists',
                              'triggering_factor': 'Memory',
                              'factor_value': 'possible_deficit',
                              'activation_weight': 0.75,
                              'computed_activation_score': None,
                              'text_effect': 'Summarize key information as '
                                             'bullet points',
                              'text_features': ['Paragraph density',
                                                'List structure']},
                             {'category': 'Content - Good Practices',
                              'adaptation_element': 'Repeat Information',
                              'triggering_factor': 'Memory',
                              'factor_value': 'possible_deficit',
                              'activation_weight': 0.75,
                              'computed_activation_score': None,
                              'text_effect': 'Repeat the main message near the '
                                             'end',
                              'text_features': ['Information repetition']},
                             {'category': 'Content - Syntax & Grammar',
                              'adaptation_element': 'No conditionals',
                              'triggering_factor': 'Worry / anxiety',
                              'factor_value': 0.85,
                              'activation_weight': 0.85,
                              'computed_activation_score': 0.7224999999999999,
                              'text_effect': 'Avoid conditional phrasing that '
                                             'may increase anxiety',
                              'text_features': ['Conditional complexity']},
                             {'category': 'Content - Good Practices',
                              'adaptation_element': 'Positive information '
                                                    'first',
                              'triggering_factor': 'Worry / anxiety',
                              'factor_value': 0.85,
                              'activation_weight': 0.85,
                              'computed_activation_score': 0.7224999999999999,
                              'text_effect': 'Mention slow progression and '
                                             'regular monitoring early',
                              'text_features': ['Positive framing']},
                             {'category': 'Content - Good Practices',
                              'adaptation_element': "Reassurance (it's ok "
                                                    'phrases)',
                              'triggering_factor': 'Worry / anxiety',
                              'factor_value': 0.85,
                              'activation_weight': 0.85,
                              'computed_activation_score': 0.7224999999999999,
                              'text_effect': 'Add one calming sentence after '
                                             'explaining the diagnosis',
                              'text_features': ['Emotional framing']},
                             {'category': 'Content - Syntax & Grammar',
                              'adaptation_element': 'Secondary sentences',
                              'triggering_factor': 'Educational level',
                              'factor_value': 'middle_school_graduate',
                              'activation_weight': 0.7,
                              'computed_activation_score': None,
                              'text_effect': 'Avoid long subordinate clauses',
                              'text_features': ['Sentence complexity']},
                             {'category': 'Morphology / Formatting',
                              'adaptation_element': 'Font Size',
                              'triggering_factor': 'Age',
                              'factor_value': 'elderly_65_plus',
                              'activation_weight': 0.65,
                              'computed_activation_score': None,
                              'text_effect': 'Support larger readable text in '
                                             'the demo or output',
                              'text_features': ['Visual accessibility']},
                             {'category': 'Content - Good Practices',
                              'adaptation_element': 'Order of information',
                              'triggering_factor': 'Uncertainty',
                              'factor_value': 0.8,
                              'activation_weight': 0.8,
                              'computed_activation_score': 0.6400000000000001,
                              'text_effect': 'Start with stabilizing '
                                             'information then explain disease '
                                             'details',
                              'text_features': ['Information order']},
                             {'category': 'Morphology / Formatting',
                              'adaptation_element': 'Enumeration (Steps)',
                              'triggering_factor': 'Processing speed',
                              'factor_value': 'possible_deficit',
                              'activation_weight': 0.6,
                              'computed_activation_score': None,
                              'text_effect': 'Present key information step by '
                                             'step',
                              'text_features': ['Sequential structure']}]}