"""
Reasoning layer for HEALIE's Otto vertical slice.

This module converts retrieved Neo4j data into:
1. A human-readable reasoning report.
2. A machine-readable reasoning object.

No LLM is used here. This layer is deterministic and based only on the
retrieved graph data.
"""

from __future__ import annotations

from collections import defaultdict
from pprint import pprint
from typing import Any

from rag_pipeline.retrieval.otto_retrieval import get_otto_retrieval_bundle
from pathlib import Path
import os

def _score_sort_value(row: dict[str, Any], weight_key: str) -> float:
    """
    Return a sortable score.

    If a computed score exists, prefer it. Otherwise use the model-level weight.
    This allows numeric patient factors to be ranked using factor_value * weight,
    while categorical factors are still ranked by stable model-level weight.
    """
    computed_score = row.get("computed_influence_score") or row.get(
        "computed_activation_score"
    )

    if computed_score is not None:
        return float(computed_score)

    weight = row.get(weight_key)
    if weight is None:
        return 0.0

    return float(weight)


def get_dominant_barriers(
    weighted_factors: list[dict[str, Any]],
    top_n: int | None = None,
) -> list[dict[str, Any]]:
    """
    Rank Otto's health-literacy barriers.

    The output preserves both:
    - patient-specific factor values
    - stable model-level influence weights
    """
    sorted_factors = sorted(
        weighted_factors,
        key=lambda row: _score_sort_value(row, "influence_weight"),
        reverse=True,
    )

    if top_n is not None:
        sorted_factors = sorted_factors[:top_n]

    barriers = []

    for row in sorted_factors:
        barriers.append(
            {
                "factor_id": row["factor_id"],
                "factor": row["factor"],
                "factor_type": row["factor_type"],
                "factor_value": row["factor_value"],
                "factor_value_type": row["factor_value_type"],
                "health_literacy_dimension": row["health_literacy_dimension"],
                "influence_weight": row["influence_weight"],
                "computed_influence_score": row["computed_influence_score"],
                "direction": row["direction"],
                "effect": row["effect"],
                "evidence_status": row["relationship_evidence_status"],
                "needs_validation": row["relationship_needs_validation"],
            }
        )

    return barriers


def group_adaptations_by_category(
    adaptations: list[dict[str, Any]],
) -> dict[str, list[dict[str, Any]]]:
    """
    Group activated adaptation elements by adaptation category.
    """
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)

    for row in adaptations:
        category = row["adaptation_category"]

        grouped[category].append(
            {
                "adaptation_element_id": row["adaptation_element_id"],
                "adaptation_element": row["adaptation_element"],
                "triggering_factor": row["triggering_factor"],
                "factor_value": row["factor_value"],
                "factor_value_type": row["factor_value_type"],
                "activation_weight": row["activation_weight"],
                "computed_activation_score": row["computed_activation_score"],
                "text_effect": row["text_effect"],
                "modified_text_features": row["modified_text_features"],
                "evidence_status": row["evidence_status"],
                "needs_validation": row["needs_validation"],
            }
        )

    for category, items in grouped.items():
        grouped[category] = sorted(
            items,
            key=lambda item: (
                item["computed_activation_score"]
                if item["computed_activation_score"] is not None
                else item["activation_weight"]
            ),
            reverse=True,
        )

    return dict(grouped)


def get_adaptation_instructions(
    grouped_adaptations: dict[str, list[dict[str, Any]]],
) -> list[dict[str, Any]]:
    """
    Flatten grouped adaptations into prompt-ready adaptation instructions.

    These instructions are still deterministic. They are not generated by an LLM.
    """
    instructions = []

    for category, items in grouped_adaptations.items():
        for item in items:
            text_features = [
                feature["text_feature"]
                for feature in item["modified_text_features"]
                if feature.get("text_feature") is not None
            ]

            instructions.append(
                {
                    "category": category,
                    "adaptation_element": item["adaptation_element"],
                    "triggering_factor": item["triggering_factor"],
                    "factor_value": item["factor_value"],
                    "activation_weight": item["activation_weight"],
                    "computed_activation_score": item["computed_activation_score"],
                    "text_effect": item["text_effect"],
                    "text_features": text_features,
                }
            )

    return sorted(
        instructions,
        key=lambda item: (
            item["computed_activation_score"]
            if item["computed_activation_score"] is not None
            else item["activation_weight"]
        ),
        reverse=True,
    )


def build_human_readable_report(reasoning_bundle: dict[str, Any]) -> str:
    """
    Build a human-readable reasoning report from the reasoning bundle.
    """
    profile = reasoning_bundle["profile"]
    barriers = reasoning_bundle["dominant_barriers"]
    grouped_adaptations = reasoning_bundle["adaptations_by_category"]
    adaptation_instructions = reasoning_bundle["adaptation_instructions"]

    lines = []

    lines.append("# Otto Reasoning Report")
    lines.append("")
    lines.append("## Patient profile")
    lines.append("")
    lines.append(f"- Patient: {profile['patient_name']}")
    lines.append(
        f"- Condition: {profile['condition_name']} ({profile['condition_abbreviation']})"
    )
    lines.append(f"- Age group: {profile['age_group']}")
    lines.append(f"- Education level: {profile['education_level']}")
    lines.append(f"- Health literacy level: {profile['health_literacy_level']}")
    lines.append(f"- Main communication need: {profile['main_communication_need']}")
    lines.append("")

    lines.append("## Dominant health-literacy barriers")
    lines.append("")

    for index, barrier in enumerate(barriers, start=1):
        computed = barrier["computed_influence_score"]
        computed_text = f"{computed:.3f}" if computed is not None else "not computed"

        lines.append(
            f"{index}. **{barrier['factor']}** "
            f"(value: `{barrier['factor_value']}`, "
            f"dimension: `{barrier['health_literacy_dimension']}`, "
            f"influence_weight: `{barrier['influence_weight']}`, "
            f"computed_score: `{computed_text}`)"
        )
        lines.append(f"   - Effect: {barrier['effect']}")
        lines.append(
            f"   - Evidence: {barrier['evidence_status']}; "
            f"needs validation: {barrier['needs_validation']}"
        )

    lines.append("")
    lines.append("## Activated adaptation elements by category")
    lines.append("")

    for category, items in grouped_adaptations.items():
        lines.append(f"### {category}")
        lines.append("")

        for item in items:
            computed = item["computed_activation_score"]
            computed_text = f"{computed:.3f}" if computed is not None else "not computed"

            feature_names = [
                feature["text_feature"]
                for feature in item["modified_text_features"]
                if feature.get("text_feature") is not None
            ]

            features_text = ", ".join(feature_names) if feature_names else "None"

            lines.append(f"- **{item['adaptation_element']}**")
            lines.append(f"  - Triggering factor: {item['triggering_factor']}")
            lines.append(f"  - Factor value: `{item['factor_value']}`")
            lines.append(f"  - Activation weight: `{item['activation_weight']}`")
            lines.append(f"  - Computed activation score: `{computed_text}`")
            lines.append(f"  - Text effect: {item['text_effect']}")
            lines.append(f"  - Modified text feature(s): {features_text}")

        lines.append("")

    lines.append("## Prompt-ready adaptation instructions")
    lines.append("")

    for index, instruction in enumerate(adaptation_instructions, start=1):
        features = ", ".join(instruction["text_features"])
        lines.append(
            f"{index}. Use **{instruction['adaptation_element']}** "
            f"({instruction['category']}) because of "
            f"**{instruction['triggering_factor']}** "
            f"(value: `{instruction['factor_value']}`)."
        )
        lines.append(f"   - Expected text effect: {instruction['text_effect']}")
        lines.append(f"   - Text feature(s): {features}")

    lines.append("")
    lines.append("## Reasoning summary")
    lines.append("")
    lines.append(
        "Otto's profile activates adaptations mainly because of low health literacy, "
        "low medical knowledge, high worry/anxiety, high uncertainty, inferred memory "
        "difficulty, inferred processing speed difficulty, older age group, and educational level."
    )
    lines.append(
        "The strongest adaptation needs are simplified language, simplified medical terms, "
        "reassurance, positive framing, ordered information, short text blocks, bullet points, "
        "repetition, and reduced conditional or complex sentence structures."
    )
    lines.append(
        "The reasoning separates Otto-specific factor values from stable HEALIE model weights."
    )

    return "\n".join(lines)


def generate_otto_reasoning_bundle() -> dict[str, Any]:
    """
    Retrieve Otto graph data and generate reasoning outputs.
    """
    retrieval_bundle = get_otto_retrieval_bundle()

    dominant_barriers = get_dominant_barriers(
        retrieval_bundle["weighted_factors"],
        top_n=None,
    )

    adaptations_by_category = group_adaptations_by_category(
        retrieval_bundle["adaptations"]
    )

    adaptation_instructions = get_adaptation_instructions(adaptations_by_category)

    reasoning_bundle = {
        "profile": retrieval_bundle["profile"],
        "dominant_barriers": dominant_barriers,
        "adaptations_by_category": adaptations_by_category,
        "adaptation_instructions": adaptation_instructions,
    }

    reasoning_bundle["human_readable_report"] = build_human_readable_report(
        reasoning_bundle
    )

    return reasoning_bundle


def print_section(title: str) -> None:
    print("\n" + "=" * 80)
    print(title)
    print("=" * 80)


if __name__ == "__main__":
    bundle = generate_otto_reasoning_bundle()

    print_section("HUMAN-READABLE REASONING REPORT")
    print(bundle["human_readable_report"])

    print_section("MACHINE-READABLE REASONING OBJECT")
    pprint(
        {
            "profile": bundle["profile"],
            "dominant_barriers": bundle["dominant_barriers"],
            "adaptation_instructions": bundle["adaptation_instructions"],
        },
        sort_dicts=False,
    )


    project_root = Path(__file__).resolve().parents[2]
    output_path = project_root / "docs" / "use_cases" / "otto_reasoning_report.md"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(bundle["human_readable_report"], encoding="utf-8")

    print(f"Saved reasoning report to: {output_path}")